#!/usr/bin/env bash
# Print a machine.lua for this computer: built-in screen + keyboard layout.
#   tools/detect-machine.sh [KB_LAYOUT] [SCALE]   (defaults: localectl's layout, auto scale)
#   tools/detect-machine.sh --probe              print "layout variant panel mode scale"
# install.sh writes the result to ~/.config/hypr/machine.lua, which hyprland.lua
# loads after the rice's own modules. Edit that file freely; re-installs keep it.
set -euo pipefail

# Keyboard: X11 layout if set, else the console keymap mapped to an xkb name.
probe=0; [[ ${1:-} == --probe ]] && { probe=1; shift; }
layout=${1:-}
want_scale=${2:-}
variant=""
if [[ -z $layout ]] && command -v localectl >/dev/null; then
    st=$(localectl status 2>/dev/null || true)
    layout=$(awk -F': *' '/X11 Layout/ {print $2}' <<<"$st" | cut -d, -f1)
    variant=$(awk -F': *' '/X11 Variant/ {print $2}' <<<"$st" | cut -d, -f1)
    if [[ -z $layout ]]; then
        km=$(awk -F': *' '/VC Keymap/ {print $2}' <<<"$st")
        case $km in
            uk|uk-*) layout=gb ;;
            n/a|"")  layout="" ;;
            *)       layout=${km%%-*} ;;
        esac
    fi
fi
layout=${layout:-us}

# Built-in panel (eDP/LVDS/DSI): native mode from sysfs, scale so the desktop is
# under 1536 px wide (1920→1.5, 2560→2), which is what the rice's layout is sized for.
panel="" mode="" scale=""
for dir in /sys/class/drm/card*-{eDP,LVDS,DSI}-*; do
    [[ -e $dir/status && $(cat "$dir/status") == connected ]] || continue
    res=$(head -1 "$dir/modes" 2>/dev/null || true)
    [[ $res =~ ^([0-9]+)x([0-9]+) ]] || continue
    w=${BASH_REMATCH[1]} h=${BASH_REMATCH[2]}
    panel=${dir##*/}; panel=${panel#card*-}; mode="${w}x${h}"
    scale=1
    for s in 1 1.25 1.5 2 2.5 3; do
        scale=$s
        awk -v w="$w" -v s="$s" 'BEGIN { exit !(w / s < 1536) }' && break
    done
    [[ -n $want_scale ]] && scale=$want_scale
    break
done

if ((probe)); then echo "$layout ${variant:--} ${panel:--} ${mode:--} ${scale:--}"; exit 0; fi

cat <<EOF
-- Machine-specific settings, generated by install.sh on $(date +%F).
-- Safe to edit: re-running the installer never overwrites this file.
-- Keyboard layouts: \`localectl list-x11-keymap-layouts\` (e.g. us, gb, de, fr).
hl.config({ input = { kb_layout = "$layout"${variant:+, kb_variant = \"$variant\"} } })
EOF
if [[ -n $panel ]]; then
cat <<EOF

-- Built-in screen: $panel, $mode → scale $scale. Bigger scale = bigger everything.
hl.monitor({ output = "$panel", mode = "preferred", position = "0x0", scale = $scale })
EOF
else
    echo
    echo '-- No built-in screen found: monitors use Hyprland'"'"'s automatic scale.'
fi
