#!/usr/bin/env python3
"""Render palette.json into the colour files each component imports.

Every themed component reads its colours from one of these generated files,
so editing palette.json and re-running this script re-themes everything.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
P = json.loads((ROOT / "palette.json").read_text())
P = {k: v for k, v in P.items() if not k.startswith("_")}
HEADER = "Generated by tools/gen-palette.py from palette.json — do not edit."


def hexa(h, a=1.0):
    """#RRGGBB + alpha -> RRGGBBAA (no hash)."""
    return f"{h[1:]}{round(a * 255):02x}"


def rgba_css(h, a):
    r, g, b = (int(h[i:i + 2], 16) for i in (1, 3, 5))
    return f"rgba({r}, {g}, {b}, {a})"


def write(rel, text):
    path = ROOT / rel
    path.write_text(text)
    print(f"  wrote {rel}")


# GTK-style CSS (waybar, swaync, wlogout, GTK apps)
css = [f"/* {HEADER} */"]
css += [f"@define-color {k} {v};" for k, v in P.items()]
css += [
    f"@define-color base_alpha {rgba_css(P['base'], 0.82)};",
    f"@define-color surface_alpha {rgba_css(P['surface'], 0.90)};",
    f"@define-color lavender_dim {rgba_css(P['lavender'], 0.18)};",
    f"@define-color purple_dim {rgba_css(P['purple'], 0.35)};",
]
css_text = "\n".join(css) + "\n"
for rel in ("waybar/colors.css", "swaync/colors.css", "wlogout/colors.css", "gtk/colors.css"):
    write(rel, css_text)

# rofi
rasi = [f"/* {HEADER} */", "* {"]
rasi += [f"    {k}: {v};" for k, v in P.items()]
rasi += [f"    base-alpha: {P['base']}f5;", f"    lavender-dim: {P['lavender']}2e;", "}"]
write("rofi/colors.rasi", "\n".join(rasi) + "\n")

# hyprlang (hyprlock / hypridle)
hl = [f"# {HEADER}"]
hl += [f"${k} = rgb({v[1:]})" for k, v in P.items()]
hl += [f"${k}_hex = {v}" for k, v in P.items()]
# alpha variants: $name_aNN = NN% opacity
for name in ("base", "mantle", "surface", "deep", "lavender", "purple", "text", "red"):
    for a in (15, 30, 60, 80, 90):
        hl.append(f"${name}_a{a} = rgba({hexa(P[name], a / 100)})")
write("hypr/palette.conf", "\n".join(hl) + "\n")

# Hyprland Lua
lua = [f"-- {HEADER}", "local M = {}"]
lua += [f'M.{k} = "{v}"' for k, v in P.items()]
lua += [
    "-- rgba(RRGGBBAA) strings for Hyprland colour options",
    "function M.rgba(name, alpha)",
    "    local h = M[name]:sub(2)",
    '    return string.format("rgba(%s%02x)", h, math.floor((alpha or 1) * 255 + 0.5))',
    "end",
    "return M",
]
write("hypr/wanglin/palette.lua", "\n".join(lua) + "\n")

# kitty
k = {
    "foreground": P["text"], "background": P["base"],
    "selection_foreground": P["base"], "selection_background": P["lavender"],
    "cursor": P["lavender"], "cursor_text_color": P["base"],
    "url_color": P["lavender"],
    "active_border_color": P["lavender"], "inactive_border_color": P["overlay"],
    "active_tab_foreground": P["base"], "active_tab_background": P["lavender"],
    "inactive_tab_foreground": P["muted"], "inactive_tab_background": P["surface"],
    "tab_bar_background": P["mantle"],
    "color0": P["surface"], "color8": P["overlay"],
    "color1": P["red"], "color9": P["red"],
    "color2": P["green"], "color10": P["green"],
    "color3": P["yellow"], "color11": P["yellow"],
    "color4": P["lavender"], "color12": P["lavender"],
    "color5": "#D7A8F0", "color13": "#E4C4F7",
    "color6": P["cyan"], "color14": P["cyan"],
    "color7": P["silver"], "color15": P["text"],
}
write("kitty/colors.conf", f"# {HEADER}\n" + "".join(f"{a} {b}\n" for a, b in k.items()))

# qt5ct / qt6ct colour scheme. Order is QPalette::ColorRole:
# WindowText Button Light Midlight Dark Mid Text BrightText ButtonText Base
# Window Shadow Highlight HighlightedText Link LinkVisited AlternateBase
# NoRole ToolTipBase ToolTipText PlaceholderText (Accent)
def qrow(disabled=False):
    fg = P["muted"] if disabled else P["text"]
    roles = [fg, P["surface"], P["overlay"], P["deep"], P["mantle"], P["deep"],
             fg, "#ffffff", fg, P["mantle"], P["base"], "#000000",
             P["lavender"], P["base"], P["lavender"], "#D7A8F0", P["surface"],
             P["base"], P["surface"], P["text"], P["muted"], P["lavender"]]
    return ", ".join("#ff" + c[1:].lower() for c in roles)

qt = (f"# {HEADER}\n[ColorScheme]\n"
      f"active_colors={qrow()}\ndisabled_colors={qrow(True)}\ninactive_colors={qrow()}\n")
write("qt/WangLin.conf", qt)

# Kvantum also draws its controls from an SVG, so regenerate those colors too.
import subprocess
import sys
if Path('/usr/share/Kvantum/KvArcDark/KvArcDark.svg').exists():
    subprocess.run([sys.executable, str(ROOT / 'tools/gen-qt-theme.py')], check=True)
print("palette applied")
