#!/usr/bin/env python3
"""Build a matching Kvantum/KDE theme from the rice palette and installed KvArcDark."""
from pathlib import Path
import colorsys
import configparser
import json
import re

ROOT = Path(__file__).resolve().parents[1]
P = json.loads((ROOT / 'palette.json').read_text())
SOURCE = Path('/usr/share/Kvantum/KvArcDark')
TARGET = ROOT / 'qt/Kvantum/WangLin'
TARGET.mkdir(parents=True, exist_ok=True)

def tint(match):
    original = match.group(0)
    rgb = tuple(int(original[i:i+2],16)/255 for i in (1,3,5))
    hue, light, saturation = colorsys.rgb_to_hls(*rgb)
    # Retain semantic red; violet replaces Arc's blue and magenta controls.
    if saturation > .35 and light > .3:
        key = 'red' if hue < .07 or hue > .94 else 'lavender'
    elif light > .78: key = 'text'
    elif light > .52: key = 'silver'
    elif light > .37: key = 'muted'
    elif light > .29: key = 'overlay'
    elif light > .24: key = 'deep'
    elif light > .19: key = 'surface'
    elif light > .12: key = 'base'
    else: key = 'mantle'
    return P[key] + original[7:]

for suffix in ('svg','kvconfig'):
    text = (SOURCE / f'KvArcDark.{suffix}').read_text()
    text = re.sub(r'#[0-9a-fA-F]{8}\b|#[0-9a-fA-F]{6}\b',tint,text)
    if suffix == 'kvconfig':
        text = text.replace('comment=A minimalistic dark theme inspired by the Arc GTK theme',
                            'comment=Wang Lin purple variant of KvArcDark by Tsu Jan')
        text = text.replace('=white\n','='+P['text']+'\n')
        replacements = {
            'window.color':P['base'], 'base.color':P['mantle'],
            'alt.base.color':P['surface'], 'button.color':P['surface'],
            'highlight.color':P['lavender'], 'inactive.highlight.color':P['purple'],
            'text.color':P['text'], 'window.text.color':P['text'],
            'button.text.color':P['silver'], 'disabled.text.color':P['muted'],
            'highlight.text.color':P['base'], 'link.color':P['lavender'],
            'link.visited.color':'#D7A8F0', 'tooltip.text.color':P['text']}
        for key,value in replacements.items():
            text = re.sub(r'^'+re.escape(key)+r'=.*$',key+'='+value,text,flags=re.M)
    (TARGET / f'WangLin.{suffix}').write_text(text)

def rgb(value):
    h=P.get(value,value)
    return ','.join(str(int(h[i:i+2],16)) for i in (1,3,5))

scheme = configparser.ConfigParser(interpolation=None)
scheme.optionxform=str
scheme.read('/usr/share/color-schemes/KvArcDark.colors')
for role,bg,alt in [('Window','base','surface'),('View','mantle','surface'),
                    ('Button','surface','deep'),('Selection','lavender','purple'),
                    ('Tooltip','surface','deep'),('Complementary','base','surface'),
                    ('Header','base','surface')]:
    scheme['Colors:'+role] = {
        'BackgroundNormal':rgb(bg), 'BackgroundAlternate':rgb(alt),
        'ForegroundNormal':rgb('base' if role=='Selection' else 'text'),
        'ForegroundInactive':rgb('muted'), 'ForegroundActive':rgb('lavender'),
        'ForegroundLink':rgb('lavender'), 'ForegroundVisited':rgb('#D7A8F0'),
        'ForegroundNegative':rgb('red'), 'ForegroundNeutral':rgb('yellow'),
        'ForegroundPositive':rgb('green'), 'DecorationFocus':rgb('lavender'),
        'DecorationHover':rgb('purple')}
scheme['General']={'ColorScheme':'WangLin','Name':'Wang Lin Purple','shadeSortColumn':'true'}
scheme['WM']={'activeBackground':rgb('base'),'activeForeground':rgb('text'),
              'inactiveBackground':rgb('mantle'),'inactiveForeground':rgb('muted')}
with (TARGET/'WangLin.colors').open('w') as f: scheme.write(f,space_around_delimiters=False)
(TARGET/'NOTICE').write_text('Wang Lin is a recolored derivative of KvArcDark by Tsu Jan, from Kvantum.\n'
    'Upstream: https://github.com/tsujan/Kvantum\nLicense: GPL-3.0-or-later, as distributed with Kvantum.\n'
    'Generated by tools/gen-qt-theme.py using palette.json.\n')
print('Generated Kvantum controls and KDE colors in',TARGET)
