-- Generated by tools/gen-palette.py from palette.json — do not edit.
local M = {}
M.base = "#100B18"
M.mantle = "#0B0712"
M.surface = "#1A1226"
M.deep = "#251538"
M.overlay = "#3A2656"
M.purple = "#6E40A1"
M.lavender = "#B88AF5"
M.silver = "#C9C4D4"
M.muted = "#9A8FB0"
M.text = "#F2ECFA"
M.red = "#F0799B"
M.yellow = "#E9C98A"
M.green = "#9BD9B4"
M.cyan = "#8FCFE0"
-- rgba(RRGGBBAA) strings for Hyprland colour options
function M.rgba(name, alpha)
    local h = M[name]:sub(2)
    return string.format("rgba(%s%02x)", h, math.floor((alpha or 1) * 255 + 0.5))
end
return M
